services:
  - type: web
    name: mern-backend
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: <tu_mongodb_uri>
